---
- name: Installs and configures Docker
  become: true
  block:
    - name: Ensure docker is installed.
      snap:
        name: docker

    - name: Ensure group "docker" exists
      group:
        name: docker

    - name: Ensure docker users are added to the docker group.
      user:
        name: "{{ ansible_user_id }}"
        groups: docker
        append: true
