---
- name: Define Garden.io version.
  set_fact:
    version: "0.12.21"

- name: Define Garden.io destination.
  set_fact:
    install_folder: "/opt/garden/{{ version }}"

- name: "Ensure install destination for Garden.io exists"
  become: true
  file:
    dest: "{{ install_folder }}"
    state: directory

- name: "Install Garden.io"
  become: true
  unarchive:
    # yamllint disable-line rule:line-length
    src: "https://github.com/garden-io/garden/releases/download/{{ version }}/garden-{{ version }}-linux-amd64.tar.gz"
    dest: "{{ install_folder }}"
    remote_src: true
    creates: "{{ install_folder }}/linux-amd64"

- name: "Unset existing installation for Garden.io in /usr/local/bin"
  become: true
  file:
    path: "/usr/local/bin/garden"
    state: absent

- name: "Create symlink for Garden.io in /usr/local/bin"
  become: true
  file:
    src: "{{ install_folder }}/linux-amd64/garden"
    path: "/usr/local/bin/garden"
    state: link
