---
- name: Install vagrant
  import_tasks:
    file: tasks/install/hashicorp_product.yml
  vars:
    name: vagrant
    version: 2.2.6

- name: Get vagrant plugin list
  command: vagrant plugin list
  register: vagrant_plugins
  changed_when: false

- name: "Install vagrant plugins"
  command: "vagrant plugin install {{ item }}"
  when: "item not in vagrant_plugins.stdout"
  loop:
    - vagrant-bindfs
    - vagrant-hostmanager
    - vagrant-share
    - vagrant-lxd

- name: Get vagrant login info
  command: vagrant cloud auth login whoami -u modellaachen
  register: vagrant_login
  ignore_errors: true
  changed_when: false

- name: Log into vagrant
  command: |
    vagrant cloud auth login -u modellaachen \
    -t {{ env.VAGRANT_CLOUD_AUTH_TOKEN }} \
    -d {{ lookup('pipe', 'echo ${USER}_$(hostname)') }}
  when: '"username and password" in vagrant_login.stdout and env.VAGRANT_CLOUD_AUTH_TOKEN is defined'
