---
- hosts: localhost
  vars_files:
    - vars/main.yml

  tasks:
    - include_tasks: tasks/install_packages.yml
      tags:
        - install
        - install_packages

    - include_tasks: tasks/install_tooling.yml
      tags:
        - install
        - install_tooling

  post_tasks:
    - block:
        - name: (re-) render dotfiles.
          include_tasks: tasks/render_dotfiles.yml
        - name: (re-) install dotfiles using dotbot.
          command: 'sh install_dotfiles.sh'
      tags:
        - install
        - install_packages
        - install_tooling
        - dotfiles

    # - name: Clear antigen cache to install newly added bundles.
    #   shell: sudo -iu {{ansible_user_id}} antigen reset