---
- include_tasks: tasks/install/docker.yml
  when: install.docker

- include_tasks: tasks/install/zsh.yml
  when: install.zsh

- include_tasks: tasks/install/gcloud-sdk.yml
  when: install.gcloud_sdk

- include_tasks: tasks/install/terraform.yml
  when: install.terraform

- include_tasks: tasks/install/packer.yml
  when: install.packer

- include_tasks: tasks/install/vault.yml
  when: install.vault

- include_tasks: tasks/install/golang.yml
  when: install.golang