---
- name: Add golang backports repository
  become: true
  apt_repository:
    repo: ppa:longsleep/golang-backports

- name: Install go-lang
  become: true
  apt:
    update_cache: true
    name: golang-go
    state: present