---
- name: Install docker python lib
  include_role:
    name: geerlingguy.pip
  vars:
    pip_install_packages:
      - name: docker
        version: "{{ tooling.version.docker.python_lib }}"

- name: Installs and configures Docker
  homebrew_cask:
    name: docker
    accept_external_apps: true
    state: installed

- name: Create custom network bridge for k8s operations.
  include_tasks:
      file: tasks/docker/docker_create_k8s_bridge.yml
