---
- stat:
    path: "{{ ansible_env.HOME }}/.local/share/mkcert/rootCA.pem"
  register: root_ca_folder

- name: Create local CA
  command: mkcert -install
  when: not root_ca_folder.stat.exists

- name: Create certificates
  include_tasks: tasks/certificates/generate_certificate.yml
  vars:
    host: "{{ item.host }}"
    location: "{{ item.location }}"
  loop: "{{ dev.certificates }}"
