---
- name: Ensure python-apt is installed.
  apt:
    name: "python3-apt"

- name: Ensure common packages are installed.
  apt:
    name: "{{ all_packages }}"

- name: Update restic
  command: restic self-update
